<?php

namespace App\Services\Chatbot\Context;

final class ChatbotKeywords
{
  public const COUPON = ['ma giam gia', 'mã giảm giá', 'giam gia', 'giảm giá', 'ma khuyen mai', 'mã khuyến mãi', 'khuyen mai', 'khuyến mãi', 'voucher', 'coupon', 'code giam', 'code giảm', 'discount code', 'promo code', 'promotion code', 'ma uu dai', 'mã ưu đãi', 'uu dai', 'ưu đãi'];

  public const PRODUCT = ['sản phẩm', 'san pham', 'mặt hàng', 'mat hang', 'đặt hàng', 'dat hang', 'mua', 'muốn mua', 'đặt', 'dat', 'bán', 'ban', 'tìm', 'tim', 'tìm kiếm', 'tim kiem', 'tra cứu', 'tra cuu', 'gợi ý', 'goi y', 'đề xuất', 'de xuat', 'recommend', 'recommendation', 'suggest', 'suggestion', 'tư vấn', 'tu van', 'giới thiệu', 'gioi thieu', 'so sánh', 'so sanh', 'nên mua', 'nen mua', 'mẫu nào', 'mau nao', 'loại nào', 'loai nao', 'thông tin', 'thong tin', 'chi tiết', 'chi tiet', 'mô tả', 'mo ta', 'cấu hình', 'cau hinh', 'thông số', 'thong so', 'đánh giá', 'danh gia', 'review', 'còn hàng', 'con hang', 'có hàng', 'co hang', 'giá', 'gia', 'bao nhiêu', 'bao nhieu', 'laptop', 'máy tính', 'may tinh', 'notebook', 'điện thoại', 'dien thoai', 'phone', 'tai nghe', 'chuột', 'ban phim', 'màn hình', 'man hinh'];

  public const ORDER = ['đơn', 'don', 'đơn hàng', 'don hang', 'order', 'invoice', 'mã đơn', 'ma don', 'mã đơn hàng', 'ma don hang', 'tracking', 'track', 'track đơn', 'theo dõi', 'theo doi', 'trạng thái', 'trang thai', 'tình trạng', 'tinh trang', 'đang ở đâu', 'dang o dau', 'đơn của tôi', 'don cua toi', 'đơn tôi', 'don toi', 'kiểm tra', 'kiem tra', 'tra cứu', 'tra cuu', 'xem đơn', 'xem don', 'lịch sử đơn', 'lich su don', 'chi tiết đơn', 'chi tiet don', 'giao tới', 'giao toi', 'giao hàng', 'giao hang', 'vận chuyển', 'van chuyen', 'ship', 'shipping', 'đơn vị vận chuyển', 'don vi van chuyen', 'mã vận đơn', 'ma van don', 'vận đơn', 'van don', 'bill', 'khi nào giao', 'khi nao giao', 'bao giờ giao', 'bao gio giao', 'đã giao chưa', 'da giao chua', 'chưa nhận', 'chua nhan', 'không nhận được', 'khong nhan duoc', 'thất lạc', 'that lac', 'hoàn hàng', 'hoan hang', 'đổi trả', 'doi tra', 'hủy đơn', 'huy don', 'cancel', 'cancel order'];

  public const SHIPPING = ['ship', 'shipping', 'vận chuyển', 'van chuyen', 'giao hàng', 'giao hang', 'giao', 'giao tới', 'giao toi', 'phí', 'phi', 'phí ship', 'phi ship', 'phí vận chuyển', 'phi van chuyen', 'cước', 'cuoc', 'cước phí', 'cuoc phi', 'tiền ship', 'tien ship', 'tiền vận chuyển', 'tien van chuyen', 'bao nhiêu tiền ship', 'bao nhieu tien ship', 'ship bao nhiêu', 'ship bao nhieu', 'tính phí ship', 'tinh phi ship', 'miễn ship', 'mien ship', 'freeship', 'free ship', 'free shipping', 'ship nhanh', 'giao nhanh', 'giao hỏa tốc', 'giao hoa toc', 'hỏa tốc', 'hoa toc', 'giao tiêu chuẩn', 'giao tieu chuan', 'ship cod', 'cod'];

  public const STOP_WORDS = ['toi', 'tôi', 'minh', 'mình', 'em', 'anh', 'chi', 'chị', 'ban', 'bạn', 'ad', 'shop', 'muon', 'muốn', 'can', 'cần', 'hoi', 'hỏi', 'la', 'là', 'va', 'và', 'hoac', 'hoặc', 'cho', 'giup', 'giúp', 'xin', 'vui', 'lòng', 'nhe', 'nhé', 'voi', 'với', 'dum', 'dùm', 'ho', 'hộ', 'cam', 'cảm', 'ơn', 'thank', 'thanks', 'ok', 'oke', 'okay', 'da', 'đã', 'dang', 'đang', 'se', 'sẽ', 'nua', 'nữa', 'roi', 'rồi', 'nha', 'nhà', 'a', 'ạ', 'n', 'nè', 'd', 'đi', 'di', 'the', 'thế', 'nao', 'nào', 'sao', 'vay', 'vậy', 'duoc', 'được', 'khong', 'không', 'ko', 'k', 'gia', 'giá', 'bao', 'nhiêu', 'nhieu', 'tien', 'tiền', 'gia bao nhieu', 'giá bao nhiêu', 'hang', 'hàng', 'san', 'phẩm', 'san pham', 'sản phẩm', 'sp', 'mat hang', 'mặt hàng', 'mon', 'món', 'loai', 'loại', 'mau', 'mẫu', 'size', 'kich co', 'kích cỡ', 'mau sac', 'màu sắc', 'màu', 'con', 'còn', 'het', 'hết', 'con hang', 'còn hàng', 'het hang', 'hết hàng', 'ship', 'shipping', 'freeship', 'free ship', 'van chuyen', 'vận chuyển', 'phi ship', 'phí ship', 'giao', 'giao hang', 'giao hàng', 'nhan', 'nhận', 'dat', 'đặt', 'dat hang', 'đặt hàng', 'mua', 'tim', 'tìm', 'kiem', 'kiếm', 'goi y', 'gợi ý', 'recommend', 'suggest', 'tu van', 'tư vấn', 'thong', 'tin', 'tiet', 've', 'dưới', 'duoi', 'triệu', 'trieu', 'nghìn', 'nghin'];
}
