<?php

return [
  'time_zone' => [
    'Pacific/Midway' => '(UTC-11:00) Midway',
    'Pacific/Honolulu' => '(UTC-10:00) Honolulu',
    'America/Anchorage' => '(UTC-09:00) Anchorage',
    'America/Los_Angeles' => '(UTC-08:00) Los Angeles',
    'America/Phoenix' => '(UTC-07:00) Phoenix',
    'America/Chicago' => '(UTC-06:00) Chicago',
    'America/New_York' => '(UTC-05:00) New York',
    'America/Santiago' => '(UTC-04:00) Santiago',
    'America/Sao_Paulo' => '(UTC-03:00) Sao Paulo',
    'America/Noronha' => '(UTC-02:00) Noronha',
    'Atlantic/Azores' => '(UTC-01:00) Azores',
    'Europe/London' => '(UTC+00:00) London',
    'Europe/Berlin' => '(UTC+01:00) Berlin',
    'Europe/Istanbul' => '(UTC+02:00) Istanbul',
    'Europe/Moscow' => '(UTC+03:00) Moscow',
    'Asia/Dubai' => '(UTC+04:00) Dubai',
    'Asia/Karachi' => '(UTC+05:00) Karachi',
    'Asia/Dhaka' => '(UTC+06:00) Dhaka',
    'Asia/Ho_Chi_Minh' => '(UTC+07:00) Ho Chi Minh',
    'Asia/Singapore' => '(UTC+08:00) Singapore',
    'Asia/Tokyo' => '(UTC+09:00) Tokyo',
    'Australia/Sydney' => '(UTC+10:00) Sydney',
    'Pacific/Pohnpei' => '(UTC+11:00) Pohnpei',
    'Pacific/Wallis' => '(UTC+12:00) Wallis',
  ],

  'address' => [
    1 => 'Tuyên Quang',
    2 => 'Cao Bằng',
    3 => 'Lai Châu',
    4 => 'Lào Cai',
    5 => 'Thái Nguyên',
    6 => 'Điện Biên',
    7 => 'Lạng Sơn',
    8 => 'Sơn La',
    9 => 'Phú Thọ',
    10 => 'Bắc Ninh',
    11 => 'Quảng Ninh',
    12 => 'TP. Hà Nội',
    13 => 'TP. Hải Phòng',
    14 => 'Hưng Yên',
    15 => 'Ninh Bình',
    16 => 'Thanh Hóa',
    17 => 'Nghệ An',
    18 => 'Hà Tĩnh',
    19 => 'Quảng Trị',
    20 => 'TP. Huế',
    21 => 'TP. Đà Nẵng',
    22 => 'Quảng Ngãi',
    23 => 'Gia Lai',
    24 => 'Đắk Lắk',
    25 => 'Khánh Hoà',
    26 => 'Lâm Đồng',
    27 => 'Đồng Nai',
    28 => 'Tây Ninh',
    29 => 'TP. Hồ Chí Minh',
    30 => 'Đồng Tháp',
    31 => 'An Giang',
    32 => 'Vĩnh Long',
    33 => 'TP. Cần Thơ',
    34 => 'Cà Mau',
  ],
];
